### ISSUE TITLE
platformIO errors

### ISSUE THREAD

**Issue by 1josh13** [codewitch-honey-crisis/EspDisplayS3#1]
Hello, 

I wanted to download this and try it out on my board. I purchased a https://www.makerfabs.com/esp32-s3-parallel-tft-with-touch-ili9488.html

These are the errors I am getting when preforming a build action in platformIO on vscode. 
```
src/main.cpp: In function 'void setup()':
src/main.cpp:82:5: error: 'main_screen' was not declared in this scope
     main_screen.background_color(color_t::white);
     ^~~~~~~~~~~
src/main.cpp:82:34: error: 'color_t' has not been declared
     main_screen.background_color(color_t::white);
                                  ^~~~~~~
src/main.cpp:84:5: error: 'test_label' was not declared in this scope
     test_label.bounds(srect16(spoint16(10,10),ssize16(200,60)));
     ^~~~~~~~~~
src/main.cpp:94:5: error: 'test_button' was not declared in this scope
     test_button.bounds(srect16(spoint16(25,25),ssize16(200,100)));
     ^~~~~~~~~~~
src/main.cpp: In lambda function:
src/main.cpp:106:75: error: 'test_button' is not captured
     test_button.on_pressed_changed_callback([](bool pressed,void* state) {test_button.text(pressed?"Pressed":"Released");});
                                                                           ^~~~~~~~~~~
src/main.cpp:106:46: note: the lambda has no capture-default
     test_button.on_pressed_changed_callback([](bool pressed,void* state) {test_button.text(pressed?"Pressed":"Released");});
                                              ^
src/main.cpp:94:5: note: '<typeprefixerror>test_button' declared here
     test_button.bounds(srect16(spoint16(25,25),ssize16(200,100)));
     ^~~~~~~~~~~
src/main.cpp: In function 'void setup()':
src/main.cpp:109:5: error: 'test_canvas' was not declared in this scope
     test_canvas.bounds(srect16(spoint16(100,25),ssize16(175,105)));
     ^~~~~~~~~~~
src/main.cpp: In function 'void loop()':
src/main.cpp:118:5: error: 'main_screen' was not declared in this scope
     main_screen.update();
     ^~~~~~~~~~~
 ```

**Comment by codewitch-honey-crisis** [comment]
Wow yeah, that's a really old project, and I've since updated dependent libraries with breaking changes. Since you're using this, I'll go ahead and work on it to bring it up to date for you now. I cannot test that it still works as I rolled over this makerfabs with an office chair. Oof. That said, I can get it to compile for you. There are newer projects that use this device, like esp_mon2

**Comment by codewitch-honey-crisis** [comment]
Try it now. You'll probably want to delete and recheck out the project as I have removed files from the original

**Comment by 1josh13** [comment]
Thank you so much for taking the time to bring this back. I know my way around c++ enough to tweak things but not solve larger issues. I can say that it builds and I can upload it to my board but it just displays a white screen. I did make a couple adjustments to the PIN config file in the LCD_controller folder but that doesnt correct the issue. Monitoring serial I just see the SRAM and block outputs as expected. 

Thank you again

**Comment by codewitch-honey-crisis** [comment]
Unfortunately I cannot debug this for you since i no longer have the device. However, my brother-in-law does, since I made him a [project with it](https://github.com/codewitch-honey-crisis/esp_mon2). 

That project should work for you.
